general.import = ["~/.config/alacritty/kanagawa-wave.toml"]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
shape = "block"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/bash"

[window]
opacity = 0.9
# dimensions.columns = 200
# dimensions.lines = 50

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 7
y = 7
